import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  value: 0,
};
// reducers objects passed to createslice  which contains a set of pure functions that handle specific actions  and the actions object generated by createSlice function which contains some actions creators that can be used to dispatch the corresponding actions
export const CounterSlice = createSlice({
  name: "counter",
  initialState,
  // define functionality

  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
  },
});

export const { increment, decrement } = CounterSlice.actions;
// reducers are the only way to update the state in redux application
export default CounterSlice.reducer;
